INSERT INTO [Categoria] ([Name]) VALUES('Backend')
INSERT INTO [Categoria] ([Name]) VALUES('Frontend')
INSERT INTO [Categoria] ([Name]) VALUES('Mobile')

INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(1, 'C#')
INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(2, 'HTML')
INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(3, 'Kotlin')
INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(1, 'Java')
INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(2, 'CSS')
INSERT INTO [Curso] ([CategoriaId], [Name]) VALUES(3, 'Swift')